//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyalexJson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contrato()
        {
            this.entregas = new HashSet<entrega>();
        }
    
        public int id_contrato { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_cliente { get; set; }
        public int id_alquiler { get; set; }
        public int dias { get; set; }
        public decimal precio { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string referencia { get; set; }
        public string tipo_pago { get; set; }
        public string num_referencia { get; set; }
        public decimal total_renta { get; set; }
        public int id_vehiculo { get; set; }
    
        public virtual alquilere alquilere { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual vehiculo vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entrega> entregas { get; set; }
    }
}
