//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyalexJson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entrega
    {
        public int id_entrega { get; set; }
        public string kilometraje { get; set; }
        public string descripestado_entrega { get; set; }
        public string descripestado_devolucion { get; set; }
        public string fecha_entrega { get; set; }
        public string fecha_devolucion { get; set; }
        public int id_cliente { get; set; }
        public int id_empleado { get; set; }
        public int id_vehiculo { get; set; }
        public int id_contrato { get; set; }
        public byte[] imagenestado_entrega { get; set; }
        public byte[] imagenestado_devolucion { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual contrato contrato { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
