//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyalexJson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public int id_reserva { get; set; }
        public int id_cliente { get; set; }
        public int id_vehiculo { get; set; }
        public decimal costoestimado { get; set; }
        public int id_empleado { get; set; }
        public string hora { get; set; }
        public string fecha { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
